"""Seed the database with dummy data for TUI demo purposes."""

import asyncio

from db import get_db, queries
from db.tables import Campaign, Deal, EmailSent, Lead, Mailbox, SequenceStep


async def seed():
    async with get_db() as db:
        # --- Leads (40 diverse leads) ---
        lead_data = [
            # Austin, TX cluster
            Lead(
                email="alice@brightsmiledental.com",
                first_name="Alice",
                last_name="Johnson",
                company="Bright Smile Dental",
                job_title="Owner",
                city="Austin",
                state="TX",
                website="https://brightsmiledental.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="maya@zentherapy.com",
                first_name="Maya",
                last_name="Nguyen",
                company="Zen Therapy",
                job_title="Therapist",
                city="Austin",
                state="TX",
                website="https://zentherapy.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="rick@austinplumbing.com",
                first_name="Rick",
                last_name="Hernandez",
                company="Austin Plumbing Co",
                job_title="Owner",
                city="Austin",
                state="TX",
                website="https://austinplumbing.com",
                source="yelp",
                email_status="valid",
            ),
            Lead(
                email="tina@longhornaccounting.com",
                first_name="Tina",
                last_name="Brooks",
                company="Longhorn Accounting",
                job_title="CPA",
                city="Austin",
                state="TX",
                website="https://longhornaccounting.com",
                source="csv_import",
                email_status="valid",
            ),
            # Dallas, TX cluster
            Lead(
                email="bob@jonesortho.com",
                first_name="Bob",
                last_name="Jones",
                company="Jones Orthodontics",
                job_title="Orthodontist",
                city="Dallas",
                state="TX",
                website="https://jonesortho.com",
                source="yelp",
                email_status="valid",
            ),
            Lead(
                email="wendy@dallashvac.com",
                first_name="Wendy",
                last_name="Park",
                company="Dallas HVAC Pros",
                job_title="Manager",
                city="Dallas",
                state="TX",
                website="https://dallashvac.com",
                source="google_maps",
                email_status="catch_all",
            ),
            # Houston, TX
            Lead(
                email="olivia@clearwater.com",
                first_name="Olivia",
                last_name="White",
                company="Clearwater Plumbing",
                job_title="Owner",
                city="Houston",
                state="TX",
                website="https://clearwater.com",
                source="yelp",
                email_status="valid",
            ),
            Lead(
                email="sam@houstonautobody.com",
                first_name="Sam",
                last_name="Reed",
                company="Houston Auto Body",
                job_title="Owner",
                city="Houston",
                state="TX",
                website="https://houstonautobody.com",
                source="google_maps",
                email_status="valid",
            ),
            # Phoenix, AZ
            Lead(
                email="carol@sunsetvet.com",
                first_name="Carol",
                last_name="Lee",
                company="Sunset Veterinary",
                job_title="DVM",
                city="Phoenix",
                state="AZ",
                website="https://sunsetvet.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="derek@desertroofing.com",
                first_name="Derek",
                last_name="Fox",
                company="Desert Roofing",
                job_title="Contractor",
                city="Phoenix",
                state="AZ",
                website="https://desertroofing.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="nina@phoenixpilates.com",
                first_name="Nina",
                last_name="Volkov",
                company="Phoenix Pilates",
                job_title="Instructor",
                city="Phoenix",
                state="AZ",
                website="https://phoenixpilates.com",
                source="yelp",
                email_status="risky",
            ),
            # Denver, CO
            Lead(
                email="dave@precisionauto.com",
                first_name="Dave",
                last_name="Martinez",
                company="Precision Auto",
                job_title="Manager",
                city="Denver",
                state="CO",
                website="https://precisionauto.com",
                source="csv_import",
                email_status="valid",
            ),
            Lead(
                email="leo@alpineconst.com",
                first_name="Leo",
                last_name="Garcia",
                company="Alpine Construction",
                job_title="Foreman",
                city="Denver",
                state="CO",
                website="https://alpineconst.com",
                source="csv_import",
                email_status="valid",
            ),
            Lead(
                email="pat@milehighcatering.com",
                first_name="Pat",
                last_name="O'Brien",
                company="Mile High Catering",
                job_title="Chef",
                city="Denver",
                state="CO",
                website="https://milehighcatering.com",
                source="exa",
                email_status="valid",
            ),
            # Portland, OR
            Lead(
                email="emma@greenleaf.com",
                first_name="Emma",
                last_name="Wilson",
                company="Greenleaf Landscaping",
                job_title="Owner",
                city="Portland",
                state="OR",
                website="https://greenleaf.com",
                source="google_maps",
                email_status="catch_all",
            ),
            Lead(
                email="nate@foxtrail.com",
                first_name="Nate",
                last_name="Robinson",
                company="Fox Trail Adventures",
                job_title="Guide",
                city="Portland",
                state="OR",
                website="https://foxtrail.com",
                source="google_maps",
                email_status="invalid",
            ),
            Lead(
                email="zoe@pdxbakery.com",
                first_name="Zoe",
                last_name="Cheng",
                company="PDX Artisan Bakery",
                job_title="Baker",
                city="Portland",
                state="OR",
                website="https://pdxbakery.com",
                source="yelp",
                email_status="valid",
            ),
            # San Francisco, CA
            Lead(
                email="frank@bluewavetech.com",
                first_name="Frank",
                last_name="Chen",
                company="BlueWave Tech",
                job_title="CTO",
                city="San Francisco",
                state="CA",
                website="https://bluewavetech.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="iris@creativestudio.com",
                first_name="Iris",
                last_name="Patel",
                company="Creative Studio",
                job_title="Designer",
                city="San Francisco",
                state="CA",
                website="https://creativestudio.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="victor@sfcloudops.com",
                first_name="Victor",
                last_name="Lam",
                company="SF CloudOps",
                job_title="DevOps Lead",
                city="San Francisco",
                state="CA",
                website="https://sfcloudops.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="diana@bayareamarketing.com",
                first_name="Diana",
                last_name="Reyes",
                company="Bay Area Marketing",
                job_title="CMO",
                city="San Francisco",
                state="CA",
                website="https://bayareamarketing.com",
                source="csv_import",
                email_status="valid",
            ),
            # Seattle, WA
            Lead(
                email="grace@peakfitness.com",
                first_name="Grace",
                last_name="Kim",
                company="Peak Fitness Studio",
                job_title="Owner",
                city="Seattle",
                state="WA",
                website="https://peakfitness.com",
                source="yelp",
                email_status="valid",
            ),
            Lead(
                email="owen@seattlewoodworks.com",
                first_name="Owen",
                last_name="Miller",
                company="Seattle Woodworks",
                job_title="Craftsman",
                city="Seattle",
                state="WA",
                website="https://seattlewoodworks.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="luna@emeraldcity.com",
                first_name="Luna",
                last_name="Sato",
                company="Emerald City Yoga",
                job_title="Instructor",
                city="Seattle",
                state="WA",
                website="https://emeraldcity.com",
                source="yelp",
                email_status="catch_all",
            ),
            # Chicago, IL
            Lead(
                email="henry@oakridgelaw.com",
                first_name="Henry",
                last_name="Taylor",
                company="Oakridge Law",
                job_title="Attorney",
                city="Chicago",
                state="IL",
                website="https://oakridgelaw.com",
                source="csv_import",
                email_status="unknown",
            ),
            Lead(
                email="mia@windycitycleaning.com",
                first_name="Mia",
                last_name="Kowalski",
                company="Windy City Cleaning",
                job_title="Owner",
                city="Chicago",
                state="IL",
                website="https://windycitycleaning.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="raj@chicagoitsolutions.com",
                first_name="Raj",
                last_name="Sharma",
                company="Chicago IT Solutions",
                job_title="CEO",
                city="Chicago",
                state="IL",
                website="https://chicagoitsolutions.com",
                source="exa",
                email_status="valid",
            ),
            # New York, NY
            Lead(
                email="sophie@nycinteriors.com",
                first_name="Sophie",
                last_name="Adams",
                company="NYC Interiors",
                job_title="Designer",
                city="New York",
                state="NY",
                website="https://nycinteriors.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="marco@manhattanbistro.com",
                first_name="Marco",
                last_name="Rossi",
                company="Manhattan Bistro",
                job_title="Owner",
                city="New York",
                state="NY",
                website="https://manhattanbistro.com",
                source="yelp",
                email_status="valid",
            ),
            Lead(
                email="priya@brooklyntech.com",
                first_name="Priya",
                last_name="Desai",
                company="Brooklyn Tech Hub",
                job_title="Founder",
                city="New York",
                state="NY",
                website="https://brooklyntech.com",
                source="exa",
                email_status="valid",
            ),
            # Boston, MA
            Lead(
                email="jack@harborview.com",
                first_name="Jack",
                last_name="Brown",
                company="Harbor View Restaurant",
                job_title="Chef",
                city="Boston",
                state="MA",
                website="https://harborview.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="chloe@bostonphysio.com",
                first_name="Chloe",
                last_name="Murphy",
                company="Boston Physiotherapy",
                job_title="PT",
                city="Boston",
                state="MA",
                website="https://bostonphysio.com",
                source="yelp",
                email_status="valid",
            ),
            # Miami, FL
            Lead(
                email="karen@sunrisecafe.com",
                first_name="Karen",
                last_name="Davis",
                company="Sunrise Cafe",
                job_title="Owner",
                city="Miami",
                state="FL",
                website="https://sunrisecafe.com",
                source="yelp",
                email_status="risky",
            ),
            Lead(
                email="carlos@miamipool.com",
                first_name="Carlos",
                last_name="Vega",
                company="Miami Pool Pros",
                job_title="Technician",
                city="Miami",
                state="FL",
                website="https://miamipool.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="lina@coralrealestate.com",
                first_name="Lina",
                last_name="Torres",
                company="Coral Real Estate",
                job_title="Agent",
                city="Miami",
                state="FL",
                website="https://coralrealestate.com",
                source="csv_import",
                email_status="valid",
            ),
            # Nashville, TN
            Lead(
                email="tyler@musiccityrepair.com",
                first_name="Tyler",
                last_name="Nash",
                company="Music City Repair",
                job_title="Technician",
                city="Nashville",
                state="TN",
                website="https://musiccityrepair.com",
                source="google_maps",
                email_status="valid",
            ),
            Lead(
                email="hannah@nashvilleweddings.com",
                first_name="Hannah",
                last_name="Blake",
                company="Nashville Weddings",
                job_title="Planner",
                city="Nashville",
                state="TN",
                website="https://nashvilleweddings.com",
                source="yelp",
                email_status="valid",
            ),
            # Atlanta, GA
            Lead(
                email="james@peachtreefinancial.com",
                first_name="James",
                last_name="Walker",
                company="Peachtree Financial",
                job_title="Advisor",
                city="Atlanta",
                state="GA",
                website="https://peachtreefinancial.com",
                source="exa",
                email_status="valid",
            ),
            Lead(
                email="kenji@atlsushi.com",
                first_name="Kenji",
                last_name="Tanaka",
                company="ATL Sushi Bar",
                job_title="Owner",
                city="Atlanta",
                state="GA",
                website="https://atlsushi.com",
                source="yelp",
                email_status="unknown",
            ),
            # Misc
            Lead(
                email="elena@sunbeltinsurance.com",
                first_name="Elena",
                last_name="Campos",
                company="Sunbelt Insurance",
                job_title="Broker",
                city="San Diego",
                state="CA",
                website="https://sunbeltinsurance.com",
                source="csv_import",
                email_status="missing",
            ),
        ]
        lead_ids = []
        for lead in lead_data:
            lid = await queries.upsert_lead(db, lead)
            lead_ids.append(lid)
        print(f"  Seeded {len(lead_ids)} leads")

        # --- Mailboxes (4) ---
        mb1 = await queries.upsert_mailbox(
            db,
            Mailbox(
                email="outreach@coldpipe.io",
                smtp_host="smtp.gmail.com",
                smtp_port=587,
                smtp_user="outreach@coldpipe.io",
                smtp_pass="demo-pass",
                imap_host="imap.gmail.com",
                imap_port=993,
                imap_user="outreach@coldpipe.io",
                imap_pass="demo-pass",
                daily_limit=50,
                warmup_day=18,
                display_name="Alex from Coldpipe",
            ),
        )
        mb2 = await queries.upsert_mailbox(
            db,
            Mailbox(
                email="sales@coldpipe.io",
                smtp_host="smtp.gmail.com",
                smtp_port=587,
                smtp_user="sales@coldpipe.io",
                smtp_pass="demo-pass",
                imap_host="imap.gmail.com",
                imap_port=993,
                imap_user="sales@coldpipe.io",
                imap_pass="demo-pass",
                daily_limit=40,
                warmup_day=12,
                display_name="Sam from Coldpipe",
            ),
        )
        mb3 = await queries.upsert_mailbox(
            db,
            Mailbox(
                email="partnerships@coldpipe.io",
                smtp_host="smtp.gmail.com",
                smtp_port=587,
                smtp_user="partnerships@coldpipe.io",
                smtp_pass="demo-pass",
                imap_host="imap.gmail.com",
                imap_port=993,
                imap_user="partnerships@coldpipe.io",
                imap_pass="demo-pass",
                daily_limit=30,
                warmup_day=5,
                display_name="Jordan from Coldpipe",
            ),
        )
        mb4 = await queries.upsert_mailbox(
            db,
            Mailbox(
                email="growth@coldpipe.io",
                smtp_host="smtp.gmail.com",
                smtp_port=587,
                smtp_user="growth@coldpipe.io",
                smtp_pass="demo-pass",
                imap_host="imap.gmail.com",
                imap_port=993,
                imap_user="growth@coldpipe.io",
                imap_pass="demo-pass",
                daily_limit=25,
                warmup_day=1,
                display_name="Riley from Coldpipe",
            ),
        )
        print("  Seeded 4 mailboxes")

        # --- Campaigns (6) ---
        c1 = await queries.create_campaign(
            db,
            Campaign(
                name="Q1 Local Business Outreach",
                status="active",
                mailbox_id=mb1,
                daily_limit=30,
            ),
        )
        c2 = await queries.create_campaign(
            db,
            Campaign(
                name="Tech Companies Intro",
                status="active",
                mailbox_id=mb2,
                daily_limit=25,
            ),
        )
        c3 = await queries.create_campaign(
            db,
            Campaign(
                name="Restaurant & Food Follow-up",
                status="paused",
                mailbox_id=mb1,
                daily_limit=15,
            ),
        )
        c4 = await queries.create_campaign(
            db,
            Campaign(
                name="Professional Services",
                status="active",
                mailbox_id=mb3,
                daily_limit=20,
            ),
        )
        c5 = await queries.create_campaign(
            db,
            Campaign(
                name="Home Services Blitz",
                status="completed",
                mailbox_id=mb2,
                daily_limit=35,
            ),
        )
        c6 = await queries.create_campaign(
            db,
            Campaign(
                name="Q2 Growth Experiment",
                status="draft",
                mailbox_id=mb4,
                daily_limit=10,
            ),
        )
        print("  Seeded 6 campaigns")

        # --- Sequence Steps (4 steps per campaign) ---
        for cid in [c1, c2, c3, c4, c5, c6]:
            await queries.add_sequence_step(
                db,
                SequenceStep(
                    campaign_id=cid,
                    step_number=0,
                    template_name="cold_intro.txt",
                    subject="Quick question about {{ company }}",
                    delay_days=0,
                ),
            )
            await queries.add_sequence_step(
                db,
                SequenceStep(
                    campaign_id=cid,
                    step_number=1,
                    template_name="followup_1.txt",
                    subject="Re: Quick question about {{ company }}",
                    delay_days=3,
                    is_reply=1,
                ),
            )
            await queries.add_sequence_step(
                db,
                SequenceStep(
                    campaign_id=cid,
                    step_number=2,
                    template_name="followup_2.txt",
                    subject="Re: Quick question about {{ company }}",
                    delay_days=4,
                    is_reply=1,
                ),
            )
            await queries.add_sequence_step(
                db,
                SequenceStep(
                    campaign_id=cid,
                    step_number=3,
                    template_name="breakup.txt",
                    subject="Re: Quick question about {{ company }}",
                    delay_days=5,
                    is_reply=1,
                ),
            )
        print("  Seeded sequence steps for all campaigns")

        # --- Enroll leads ---
        # Campaign 1 (Local Business): leads 0-11  (12 leads)
        for lid in lead_ids[:12]:
            await queries.enroll_lead(db, c1, lid)
        # Campaign 2 (Tech): leads 17-21, 26-29  (9 leads)
        for lid in lead_ids[17:22] + lead_ids[26:30]:
            await queries.enroll_lead(db, c2, lid)
        # Campaign 3 (Restaurant/Food): leads 13, 16, 28, 30, 38 (5 leads)
        for lid in [lead_ids[13], lead_ids[16], lead_ids[28], lead_ids[30], lead_ids[38]]:
            await queries.enroll_lead(db, c3, lid)
        # Campaign 4 (Professional Services): leads 3, 24, 25, 31, 34, 37 (6 leads)
        for lid in [
            lead_ids[3],
            lead_ids[24],
            lead_ids[25],
            lead_ids[31],
            lead_ids[34],
            lead_ids[37],
        ]:
            await queries.enroll_lead(db, c4, lid)
        # Campaign 5 (Home Services): leads 2, 5, 6, 7, 9, 12, 33 (7 leads)
        for lid in [
            lead_ids[2],
            lead_ids[5],
            lead_ids[6],
            lead_ids[7],
            lead_ids[9],
            lead_ids[12],
            lead_ids[33],
        ]:
            await queries.enroll_lead(db, c5, lid)
        # Campaign 6 (Q2 Growth): leads 35, 36, 37 (3 leads, draft)
        for lid in [lead_ids[35], lead_ids[36], lead_ids[37]]:
            await queries.enroll_lead(db, c6, lid)
        print("  Enrolled leads into campaigns")

        # --- Simulate sends (30+ emails across campaigns, steps, and statuses) ---
        emails_sent = [
            # Campaign 1 — step 0 (initial)
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[0],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-001",
                subject="Quick question about Bright Smile Dental",
                to_email="alice@brightsmiledental.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Alice, I noticed your practice...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[1],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-002",
                subject="Quick question about Zen Therapy",
                to_email="maya@zentherapy.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Maya, I came across Zen Therapy...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[2],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-003",
                subject="Quick question about Austin Plumbing Co",
                to_email="rick@austinplumbing.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Rick, love what you're doing...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[3],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-004",
                subject="Quick question about Longhorn Accounting",
                to_email="tina@longhornaccounting.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Tina, I noticed your firm...",
                status="bounced",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[4],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-005",
                subject="Quick question about Jones Orthodontics",
                to_email="bob@jonesortho.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Bob, I saw your practice...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[5],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-006",
                subject="Quick question about Dallas HVAC Pros",
                to_email="wendy@dallashvac.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Wendy, reaching out about...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[6],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-007",
                subject="Quick question about Clearwater Plumbing",
                to_email="olivia@clearwater.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Olivia, saw your reviews...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[7],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-008",
                subject="Quick question about Houston Auto Body",
                to_email="sam@houstonautobody.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Sam, I noticed your shop...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[8],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-009",
                subject="Quick question about Sunset Veterinary",
                to_email="carol@sunsetvet.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Carol, your clinic looks amazing...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[9],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-010",
                subject="Quick question about Desert Roofing",
                to_email="derek@desertroofing.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Derek, reaching out to...",
                status="failed",
            ),
            # Campaign 1 — step 1 (follow-up for some leads)
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[1],
                mailbox_id=mb1,
                step_number=1,
                message_id="msg-011",
                subject="Re: Quick question about Zen Therapy",
                to_email="maya@zentherapy.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Maya, just circling back...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[5],
                mailbox_id=mb1,
                step_number=1,
                message_id="msg-012",
                subject="Re: Quick question about Dallas HVAC Pros",
                to_email="wendy@dallashvac.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Wendy, wanted to follow up...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[7],
                mailbox_id=mb1,
                step_number=1,
                message_id="msg-013",
                subject="Re: Quick question about Houston Auto Body",
                to_email="sam@houstonautobody.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Sam, following up on...",
                status="delivered",
            ),
            # Campaign 1 — step 2
            EmailSent(
                campaign_id=c1,
                lead_id=lead_ids[5],
                mailbox_id=mb1,
                step_number=2,
                message_id="msg-014",
                subject="Re: Quick question about Dallas HVAC Pros",
                to_email="wendy@dallashvac.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Wendy, one more try...",
                status="bounced",
            ),
            # Campaign 2 — step 0
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[17],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-020",
                subject="Quick question about BlueWave Tech",
                to_email="frank@bluewavetech.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Frank, love what BlueWave is building...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[18],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-021",
                subject="Quick question about Creative Studio",
                to_email="iris@creativestudio.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Iris, your portfolio is stunning...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[19],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-022",
                subject="Quick question about SF CloudOps",
                to_email="victor@sfcloudops.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Victor, DevOps is our sweet spot...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[20],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-023",
                subject="Quick question about Bay Area Marketing",
                to_email="diana@bayareamarketing.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Diana, I noticed your agency...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[26],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-024",
                subject="Quick question about Chicago IT Solutions",
                to_email="raj@chicagoitsolutions.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Raj, interesting work...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[27],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-025",
                subject="Quick question about NYC Interiors",
                to_email="sophie@nycinteriors.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Sophie, love your design work...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[29],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-026",
                subject="Quick question about Brooklyn Tech Hub",
                to_email="priya@brooklyntech.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Priya, exciting community...",
                status="bounced",
            ),
            # Campaign 2 — step 1
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[18],
                mailbox_id=mb2,
                step_number=1,
                message_id="msg-027",
                subject="Re: Quick question about Creative Studio",
                to_email="iris@creativestudio.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Iris, following up...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c2,
                lead_id=lead_ids[26],
                mailbox_id=mb2,
                step_number=1,
                message_id="msg-028",
                subject="Re: Quick question about Chicago IT Solutions",
                to_email="raj@chicagoitsolutions.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Raj, circling back...",
                status="sent",
            ),
            # Campaign 3 — step 0 (paused campaign, a few sends)
            EmailSent(
                campaign_id=c3,
                lead_id=lead_ids[28],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-030",
                subject="Quick question about Manhattan Bistro",
                to_email="marco@manhattanbistro.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Marco, love the menu...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c3,
                lead_id=lead_ids[30],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-031",
                subject="Quick question about Harbor View Restaurant",
                to_email="jack@harborview.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Jack, great reviews...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c3,
                lead_id=lead_ids[38],
                mailbox_id=mb1,
                step_number=0,
                message_id="msg-032",
                subject="Quick question about ATL Sushi Bar",
                to_email="kenji@atlsushi.com",
                from_email="outreach@coldpipe.io",
                body_text="Hi Kenji, interesting concept...",
                status="sent",
            ),
            # Campaign 4 — step 0
            EmailSent(
                campaign_id=c4,
                lead_id=lead_ids[24],
                mailbox_id=mb3,
                step_number=0,
                message_id="msg-040",
                subject="Quick question about Oakridge Law",
                to_email="henry@oakridgelaw.com",
                from_email="partnerships@coldpipe.io",
                body_text="Hi Henry, I noticed your firm...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c4,
                lead_id=lead_ids[25],
                mailbox_id=mb3,
                step_number=0,
                message_id="msg-041",
                subject="Quick question about Windy City Cleaning",
                to_email="mia@windycitycleaning.com",
                from_email="partnerships@coldpipe.io",
                body_text="Hi Mia, your service reviews...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c4,
                lead_id=lead_ids[37],
                mailbox_id=mb3,
                step_number=0,
                message_id="msg-042",
                subject="Quick question about Peachtree Financial",
                to_email="james@peachtreefinancial.com",
                from_email="partnerships@coldpipe.io",
                body_text="Hi James, your advisory practice...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c4,
                lead_id=lead_ids[31],
                mailbox_id=mb3,
                step_number=0,
                message_id="msg-043",
                subject="Quick question about Boston Physiotherapy",
                to_email="chloe@bostonphysio.com",
                from_email="partnerships@coldpipe.io",
                body_text="Hi Chloe, saw your clinic...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c4,
                lead_id=lead_ids[34],
                mailbox_id=mb3,
                step_number=0,
                message_id="msg-044",
                subject="Quick question about Coral Real Estate",
                to_email="lina@coralrealestate.com",
                from_email="partnerships@coldpipe.io",
                body_text="Hi Lina, interesting listings...",
                status="replied",
            ),
            # Campaign 5 (completed) — multiple steps
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[2],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-050",
                subject="Quick question about Austin Plumbing Co",
                to_email="rick@austinplumbing.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Rick, home services...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[6],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-051",
                subject="Quick question about Clearwater Plumbing",
                to_email="olivia@clearwater.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Olivia, plumbing outreach...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[7],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-052",
                subject="Quick question about Houston Auto Body",
                to_email="sam@houstonautobody.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Sam, auto body services...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[9],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-053",
                subject="Quick question about Desert Roofing",
                to_email="derek@desertroofing.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Derek, roofing outreach...",
                status="bounced",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[12],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-054",
                subject="Quick question about Alpine Construction",
                to_email="leo@alpineconst.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Leo, construction outreach...",
                status="delivered",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[33],
                mailbox_id=mb2,
                step_number=0,
                message_id="msg-055",
                subject="Quick question about Miami Pool Pros",
                to_email="carlos@miamipool.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Carlos, pool services...",
                status="sent",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[6],
                mailbox_id=mb2,
                step_number=1,
                message_id="msg-056",
                subject="Re: Quick question about Clearwater Plumbing",
                to_email="olivia@clearwater.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Olivia, following up...",
                status="replied",
            ),
            EmailSent(
                campaign_id=c5,
                lead_id=lead_ids[12],
                mailbox_id=mb2,
                step_number=1,
                message_id="msg-057",
                subject="Re: Quick question about Alpine Construction",
                to_email="leo@alpineconst.com",
                from_email="sales@coldpipe.io",
                body_text="Hi Leo, circling back...",
                status="delivered",
            ),
        ]
        for es in emails_sent:
            await queries.log_send(db, es)
        print(f"  Seeded {len(emails_sent)} sent emails")

        # --- Deals (25+ across all 8 pipeline stages) ---
        deals = [
            # lead (new, not yet contacted)
            Deal(lead_id=lead_ids[10], campaign_id=c1, stage="lead", value=2800),
            Deal(lead_id=lead_ids[11], campaign_id=c1, stage="lead", value=4200),
            Deal(lead_id=lead_ids[19], campaign_id=c2, stage="lead", value=9500),
            Deal(lead_id=lead_ids[33], campaign_id=c5, stage="lead", value=3200),
            # contacted (email sent, no response yet)
            Deal(lead_id=lead_ids[2], campaign_id=c1, stage="contacted", value=3500),
            Deal(lead_id=lead_ids[6], campaign_id=c1, stage="contacted", value=4100),
            Deal(lead_id=lead_ids[7], campaign_id=c1, stage="contacted", value=2900),
            Deal(lead_id=lead_ids[26], campaign_id=c2, stage="contacted", value=11000),
            Deal(lead_id=lead_ids[24], campaign_id=c4, stage="contacted", value=7500),
            # replied (got a response)
            Deal(
                lead_id=lead_ids[0],
                campaign_id=c1,
                stage="replied",
                value=5000,
                notes="Interested in demo",
            ),
            Deal(
                lead_id=lead_ids[4],
                campaign_id=c1,
                stage="replied",
                value=3800,
                notes="Wants more info",
            ),
            Deal(
                lead_id=lead_ids[8],
                campaign_id=c1,
                stage="replied",
                value=6200,
                notes="Very responsive",
            ),
            Deal(
                lead_id=lead_ids[25],
                campaign_id=c4,
                stage="replied",
                value=4500,
                notes="Asked about pricing",
            ),
            # interested (positive signal)
            Deal(
                lead_id=lead_ids[17],
                campaign_id=c2,
                stage="interested",
                value=15000,
                notes="Wants a proposal",
            ),
            Deal(
                lead_id=lead_ids[1],
                campaign_id=c1,
                stage="interested",
                value=5500,
                notes="Requested case studies",
            ),
            Deal(
                lead_id=lead_ids[34],
                campaign_id=c4,
                stage="interested",
                value=8000,
                notes="Warm lead",
            ),
            # meeting_booked
            Deal(
                lead_id=lead_ids[18],
                campaign_id=c2,
                stage="meeting_booked",
                value=12000,
                notes="Demo scheduled for Monday",
            ),
            Deal(
                lead_id=lead_ids[20],
                campaign_id=c2,
                stage="meeting_booked",
                value=18000,
                notes="Call next Wednesday",
            ),
            Deal(
                lead_id=lead_ids[30],
                campaign_id=c3,
                stage="meeting_booked",
                value=5500,
                notes="Lunch meeting set",
            ),
            # proposal_sent
            Deal(
                lead_id=lead_ids[28],
                campaign_id=c3,
                stage="proposal_sent",
                value=7500,
                notes="Sent detailed SOW",
            ),
            Deal(
                lead_id=lead_ids[31],
                campaign_id=c4,
                stage="proposal_sent",
                value=9200,
                notes="Pending review",
            ),
            Deal(
                lead_id=lead_ids[2],
                campaign_id=c5,
                stage="proposal_sent",
                value=6800,
                notes="Budget discussion",
            ),
            # closed_won
            Deal(
                lead_id=lead_ids[12],
                campaign_id=c5,
                stage="closed_won",
                value=8500,
                close_date="2026-01-15",
                notes="Signed annual contract",
            ),
            Deal(
                lead_id=lead_ids[6],
                campaign_id=c5,
                stage="closed_won",
                value=6000,
                close_date="2026-01-22",
                notes="3-month pilot",
            ),
            Deal(
                lead_id=lead_ids[37],
                campaign_id=c4,
                stage="closed_won",
                value=14000,
                close_date="2026-02-01",
                notes="Full engagement",
            ),
            Deal(
                lead_id=lead_ids[7],
                campaign_id=c5,
                stage="closed_won",
                value=4200,
                close_date="2026-02-10",
                notes="Quick close",
            ),
            # closed_lost
            Deal(
                lead_id=lead_ids[3],
                campaign_id=c1,
                stage="closed_lost",
                value=3500,
                loss_reason="Budget constraints",
            ),
            Deal(
                lead_id=lead_ids[9],
                campaign_id=c1,
                stage="closed_lost",
                value=4800,
                loss_reason="Went with competitor",
            ),
            Deal(
                lead_id=lead_ids[5],
                campaign_id=c1,
                stage="closed_lost",
                value=2200,
                loss_reason="No response after follow-up",
            ),
            Deal(
                lead_id=lead_ids[29],
                campaign_id=c2,
                stage="closed_lost",
                value=7000,
                loss_reason="Bad timing",
            ),
        ]
        for deal in deals:
            await queries.upsert_deal(db, deal)
        print(f"  Seeded {len(deals)} deals")

        # --- Daily send log (realistic send counts) ---
        # mb1: 18 warmup days, should have decent daily volume
        for _ in range(14):
            await queries.increment_daily_send(db, mb1)
        # mb2: 12 warmup days
        for _ in range(9):
            await queries.increment_daily_send(db, mb2)
        # mb3: 5 warmup days, lower volume
        for _ in range(5):
            await queries.increment_daily_send(db, mb3)
        # mb4: day 1, minimal
        await queries.increment_daily_send(db, mb4)
        print("  Seeded daily send counts (14+9+5+1 = 29 total)")

    print("\nDone! Run the TUI with:  .venv/bin/python -m tui")


if __name__ == "__main__":
    asyncio.run(seed())
